# Generated by Django 3.2.8 on 2021-11-14 16:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.CharField(help_text='The number associated with this account.', max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Field must contain 8 digits.', regex='^(1-)?\\d{8}$')], verbose_name='Account Number')),
                ('name', models.CharField(help_text='The name of this account.', max_length=150, verbose_name='Account Name')),
                ('phone_number', models.CharField(help_text='The phone number associated with this account. Use format: XXX-XXX-XXXX.', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number not in required format.', regex='^(1-)?\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Phone Number')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='The monetary balance of this account.', max_digits=19, verbose_name='Balance')),
                ('user', models.ForeignKey(default=None, help_text='The user associated with this account.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Transaction Amount')),
                ('category', models.CharField(max_length=15, verbose_name='Transaction Type')),
                ('positive', models.BooleanField(default=True, verbose_name='Positive Change')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='customers.account', verbose_name='Account')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='machines.machine', verbose_name='ATM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('holder', models.CharField(blank=True, help_text='Name of the holder of this ATM card.', max_length=150, verbose_name='ATM Card Holder')),
                ('number', models.CharField(help_text='The number associated with this ATM card. Use format: XXXX-XXXX-XXXX-XXXX.', max_length=19, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Card number not in required format.', regex='^(1-)?\\d{4}-\\d{4}-\\d{4}-\\d{4}$')], verbose_name='ATM Card Number')),
                ('pin', models.CharField(help_text='The personal identification number assigned to this ATM card.', max_length=4, validators=[django.core.validators.RegexValidator(message='PIN number must be 4 digits.', regex='^(1-)?\\d{4}$')], verbose_name='PIN')),
                ('status', models.BooleanField(default=True, help_text='The current status of this ATM card.', verbose_name='Active')),
                ('date_issued', models.DateField(default=django.utils.timezone.now, help_text='The date in which this ATM card was issued.', verbose_name='Date of Issue')),
                ('expiry_date', models.DateField(help_text='The date in which this ATM card expires.', verbose_name='Expiration Date')),
                ('account', models.ForeignKey(default=None, help_text='The account associated with this ATM card.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='card', to='customers.account', verbose_name='Account')),
            ],
        ),
    ]
